language: node_js

node_js:
  - 5.7

cache:
  directories:
    - node_modules

before_script:
  - git config --global user.name 'Travis-ci'
  - git config --global user.email 'josetelesmaciel@gmail.com'

script: npm run coverage & npm run coverage-to-codacy
